@baseUrl=http://localhost:3000/api
@resouceName=products

# Products

# @name getAll
GET {{baseUrl}}/{{resouceName}}

#########

# @name filterProducts
GET {{baseUrl}}/{{resouceName}}?color=orchid&price_gte=650

#########

# @name filterProductName
GET {{baseUrl}}/{{resouceName}}?name_like=chicken

#########

# @name pagination
GET {{baseUrl}}/{{resouceName}}?_limit=5&_page=2

#########

# @name sort
GET {{baseUrl}}/{{resouceName}}?_sort=price&_order=desc

#########

# @name addNew
POST {{baseUrl}}/{{resouceName}}
Content-Type: application/json

{
  "categoryId": "f67ac936-9952-4eed-8337-8f6917cfa367",
  "name": "Unbranded Frozen Chicken 123",
  "color": "silver",
  "price": 456,
  "discription": "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
  "thumnailUrl": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/580.jpg"
}

#########

# @name update
PATCH {{baseUrl}}/{{resouceName}}/C5wxlA0
Content-Type: application/json

{
  "name": "Unbranded Frozen Chicken 123 Update",
  "color": "gold",
  "price": 546
}

#########

# @name remove
DELETE {{baseUrl}}/{{resouceName}}/2
